blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/Mauricio-JA/impostor-game-IA/discussions/new/choose
    about: Haz preguntas y discute ideas con la comunidad.
